// src/lib/components/signup/FormField.svelte
<script lang="ts">
	import { Label } from '$lib/components/ui/label';
	import {
		InputGroup,
		InputGroupAddon,
		InputGroupButton,
		InputGroupInput
	} from '$lib/components/ui/input-group';
	import {
		Tooltip,
		TooltipContent,
		TooltipTrigger,
		TooltipProvider
	} from '$lib/components/ui/tooltip';
	import { type FormFieldConfig } from '$lib/constants/signup/formFields';

	interface FormFieldProps {
		field: FormFieldConfig;
		value: string;
		onChange: (e: Event & { currentTarget: HTMLInputElement }) => void;
		disabled?: boolean;
	}

	let { field, value, onChange, disabled = false }: FormFieldProps = $props();

	const Icon = $derived(field.icon);
	const TooltipIcon = $derived(field.tooltipIcon);
</script>

<div class="space-y-2">
	<Label class="text-xl" for={String(field.id)}>
		{field.label}
	</Label>

	<InputGroup class="h-12!">
		<InputGroupInput
			type={field.type}
			id={String(field.id)}
			name={String(field.name)}
			value={value ?? ''}
			oninput={onChange}
			placeholder={field.placeholder}
			class="text-lg!"
			required
			{disabled}
		/>

		<InputGroupAddon>
			{#if Icon}
				<Icon />
			{/if}
		</InputGroupAddon>

		{#if TooltipIcon && field.tooltipContent}
			<InputGroupAddon align="inline-end">
				<TooltipProvider>
					<Tooltip>
						<TooltipTrigger>
							{#snippet child({ props })}
								<InputGroupButton {...props} class="rounded-full" size="icon-sm">
									<TooltipIcon />
								</InputGroupButton>
							{/snippet}
						</TooltipTrigger>

						<TooltipContent>
							{#each field.tooltipContent.split('\n') as line, i}
								<span>
									{line}
									{#if i < field.tooltipContent.split('\n').length - 1}
										<br />
									{/if}
								</span>
							{/each}
						</TooltipContent>
					</Tooltip>
				</TooltipProvider>
			</InputGroupAddon>
		{/if}
	</InputGroup>
</div>

// src/components/signup/FormField.tsx
import { Label } from "@/components/ui/label";
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput,
} from "@/components/ui/input-group";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
  TooltipProvider,
} from "@/components/ui/tooltip";
import { FormFieldConfig } from "@/data/signup/formFields";

interface FormFieldProps {
  field: FormFieldConfig;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  disabled?: boolean;
}

export default function FormField({
  field,
  value,
  onChange,
  disabled = false,
}: FormFieldProps) {
  const Icon = field.icon;
  const TooltipIcon = field.tooltipIcon;

  return (
    <div className="space-y-2">
      <Label className="text-xl" htmlFor={field.id}>
        {field.label}
      </Label>
      <InputGroup className="h-12!">
        <InputGroupInput
          type={field.type}
          id={field.id}
          name={field.name}
          value={value}
          onChange={onChange}
          placeholder={field.placeholder}
          className="text-lg!"
          required
          disabled={disabled}
        />
        <InputGroupAddon>
          <Icon />
        </InputGroupAddon>

        {TooltipIcon && field.tooltipContent && (
          <InputGroupAddon align="inline-end">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <InputGroupButton className="rounded-full" size="icon-sm">
                    <TooltipIcon />
                  </InputGroupButton>
                </TooltipTrigger>
                <TooltipContent>
                  {field.tooltipContent.split("\n").map((line, i) => (
                    <span key={i}>
                      {line}
                      {i < field.tooltipContent!.split("\n").length - 1 && (
                        <br />
                      )}
                    </span>
                  ))}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </InputGroupAddon>
        )}
      </InputGroup>
    </div>
  );
}
