// src/components/app/editor/EditorToolbar.tsx
"use client";

import { Editor, useEditorState } from "@tiptap/react";

import {
  Bold,
  Italic,
  Strikethrough,
  List,
  ListOrdered,
  Code,
} from "lucide-react";

import { Toggle } from "@/components/ui/toggle";

interface Props {
  editor: Editor;
}

export function EditorToolbar({ editor }: Props) {
  const state = useEditorState({
    editor,

    selector: ({ editor }) => ({
      bold: editor.isActive("bold"),
      italic: editor.isActive("italic"),
      strike: editor.isActive("strike"),
      bullet: editor.isActive("bulletList"),
      ordered: editor.isActive("orderedList"),
      code: editor.isActive("code"),
    }),
  });

  const buttons = [
    {
      icon: Bold,
      active: state.bold,
      onClick: () => editor.chain().focus().toggleBold().run(),
    },
    {
      icon: Italic,
      active: state.italic,
      onClick: () => editor.chain().focus().toggleItalic().run(),
    },
    {
      icon: Strikethrough,
      active: state.strike,
      onClick: () => editor.chain().focus().toggleStrike().run(),
    },
    {
      icon: List,
      active: state.bullet,
      onClick: () => editor.chain().focus().toggleBulletList().run(),
    },
    {
      icon: ListOrdered,
      active: state.ordered,
      onClick: () => editor.chain().focus().toggleOrderedList().run(),
    },
    {
      icon: Code,
      active: state.code,
      onClick: () => editor.chain().focus().toggleCode().run(),
    },
  ];

  return (
    <div className="mb-2 flex gap-1 px-3">
      {buttons.map((button, index) => {
        const Icon = button.icon;

        return (
          <Toggle
            key={index}
            pressed={button.active}
            onPressedChange={button.onClick}
            className="rounded p-2"
          >
            <Icon className="h-4 w-4" />
          </Toggle>
        );
      })}
    </div>
  );
}

// src/lib/components/app/editor/EditorToolbar.svelte
<script lang="ts">
	import { Bold, Italic, Strikethrough, List, ListOrdered, Code } from '@lucide/svelte';
	import { Toggle } from '$lib/components/ui/toggle';
	import type { Editor } from '@tiptap/core';

	interface Props {
		editor: Editor;
	}

	let { editor }: Props = $props();

	const buttons = [
		{
			icon: Bold,
			isActive: () => editor.isActive('bold'),
			run: () => editor.chain().focus().toggleBold().run()
		},
		{
			icon: Italic,
			isActive: () => editor.isActive('italic'),
			run: () => editor.chain().focus().toggleItalic().run()
		},
		{
			icon: Strikethrough,
			isActive: () => editor.isActive('strike'),
			run: () => editor.chain().focus().toggleStrike().run()
		},
		{
			icon: List,
			isActive: () => editor.isActive('bulletList'),
			run: () => editor.chain().focus().toggleBulletList().run()
		},
		{
			icon: ListOrdered,
			isActive: () => editor.isActive('orderedList'),
			run: () => editor.chain().focus().toggleOrderedList().run()
		},
		{
			icon: Code,
			isActive: () => editor.isActive('code'),
			run: () => editor.chain().focus().toggleCode().run()
		}
	];
</script>

<div class="mb-2 flex gap-1 px-3">
	{#each buttons as button, i (i)}
		<Toggle pressed={button.isActive()} onPressedChange={button.run} class="rounded p-2">
			<button.icon class="h-4 w-4" />
		</Toggle>
	{/each}
</div>
