// src/routes/(auth)/app/new/+page.svelte
<script lang="ts">
	import { ArrowLeft, Check, X } from '@lucide/svelte';
	import { Button } from '$lib/components/ui/button';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import Editor from '$lib/components/app/editor/Editor.svelte';
	import { useCreateEntry } from '$lib/hooks/app/useCreateEntry.svelte';

	const entry = useCreateEntry();

	let contentRef = $state('');
	let isEditorEmpty = $state(true);

	async function handleSaveAndRedirect() {
		try {
			const entryId = await entry.handleSave(contentRef);
			if (entryId) {
				const resolved = resolve('/(auth)/app/entries/[id]', { id: entryId });
				goto(resolved, { replaceState: true });
			}
		} catch (err) {
			console.error('failed to save entry:', err);
		}
	}
</script>

<main class="flex h-full flex-col px-12 py-6">
	<div class="mt-auto mb-4 flex items-center justify-between">
		<Button variant="ghost" href={resolve('/app')} class="flex items-center px-3! py-6! text-2xl">
			<ArrowLeft class="mt-1 -mr-0.5" />
			home
		</Button>

		<div class="flex gap-2">
			<Button
				variant="secondary"
				onclick={() => history.back()}
				class="flex h-10! w-10! items-center justify-center rounded-full"
			>
				<X class="h-5! w-5! stroke-3!" />
			</Button>
			<Button
				variant="default"
				onclick={handleSaveAndRedirect}
				disabled={entry.isSaving || !entry.title || isEditorEmpty}
				class="flex h-10! w-10! items-center justify-center rounded-full"
			>
				<Check class="h-5! w-5! stroke-3!" />
			</Button>
		</div>
	</div>

	<div class="px-2">
		<input
			placeholder="untitled entry"
			type="text"
			value={entry.title}
			oninput={(e) => (entry.title = e.currentTarget.value)}
			class="font-editor mb-4 w-full border-b-2 border-accent bg-transparent text-2xl outline-none placeholder:text-muted-foreground"
		/>
	</div>

	<div class="flex min-h-0 flex-1 flex-col rounded-sm border-2 bg-white/80 py-2">
		<Editor
			initialContent=""
			editable={true}
			onChange={(json) => (contentRef = json)}
			onEmptyChange={(isEmpty) => (isEditorEmpty = isEmpty)}
		/>
	</div>
</main>

// src/app/(app)/(protected)/app/new/page.tsx
"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Editor } from "@/components/app/editor/Editor";
import { useCreateEntry } from "@/hooks/app/useCreateEntry";
import { useRouter } from "next/navigation";

export default function NewEntry() {
  const router = useRouter();
  const { title, setTitle, isSaving, handleSave } = useCreateEntry();

  const contentRef = useRef("");
  const [isEditorEmpty, setIsEditorEmpty] = useState(true);

  const handleSaveAndRedirect = async () => {
    try {
      const entryId = await handleSave(contentRef.current);

      if (entryId) {
        router.push(`/app/entries/${entryId}`);
      }
    } catch (err) {
      console.error("failed to save entry:", err);
    }
  };

  return (
    <main className="flex h-full flex-col px-12 py-6">
      <div className="mt-auto mb-4 flex items-center justify-between">
        <Button
          variant="ghost"
          asChild
          className="flex items-center px-3! py-6! text-2xl"
        >
          <Link href="/app/entries">
            <ArrowLeft className="mt-1 -mr-0.5" />
            new entry
          </Link>
        </Button>

        <div className="flex gap-2">
          <Button
            variant="secondary"
            onClick={() => router.back()}
            className="flex h-10! w-10! items-center justify-center rounded-full"
          >
            <X className="h-5! w-5! stroke-3!" />
          </Button>
          <Button
            variant="default"
            onClick={handleSaveAndRedirect}
            disabled={isSaving || !title || isEditorEmpty}
            className="flex h-10! w-10! items-center justify-center rounded-full"
          >
            <Check className="h-5! w-5! stroke-3!" />
          </Button>
        </div>
      </div>

      <div className="px-2">
        {/* <h2 className="text-xl tracking-wide">title</h2> */}
        <input
          placeholder="untitled entry"
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className="placeholder:text-muted-foreground border-accent font-editor mb-4 w-full border-b-2 bg-transparent text-2xl outline-none"
        />
      </div>

      <div className="flex min-h-0 flex-1 flex-col rounded-sm border-2 bg-white/80 py-2">
        <Editor
          initialContent=""
          editable={true}
          onChange={(json) => {
            contentRef.current = json;
          }}
          onEmptyChange={(isEmpty) => setIsEditorEmpty(isEmpty)}
        />
      </div>
    </main>
  );
}
