// src/routes/(auth)/app/entries/+page.svelte
<script lang="ts">
	import EntryCard from '$lib/components/app/entry/EntryCard.svelte';
	import EmptyState from '$lib/components/app/entry/EmptyState.svelte';
	import EntriesHeader from '$lib/components/app/entry/EntriesHeader.svelte';
	import LoadingText from '$lib/components/shared/LoadingText.svelte';
	import { ScrollArea } from '$lib/components/ui/scroll-area';
	import { getAppContext } from '$lib/contexts/app.context.svelte';

	const { entries, isLoading } = getAppContext();
</script>

{#if isLoading}
	<div class="flex h-full items-center justify-center text-6xl text-muted-foreground">
		<LoadingText />
	</div>
{:else}
	<main class="flex h-full flex-col px-10 pt-12">
		<EntriesHeader entriesCount={entries.length} />

		{#if entries.length === 0}
			<EmptyState />
		{:else}
			<ScrollArea class="min-h-0 flex-1">
				<div class="mr-3 space-y-2 pb-6">
					{#each entries as entry (entry.id)}
						<EntryCard {entry} />
					{/each}
				</div>
			</ScrollArea>
		{/if}
	</main>
{/if}

// src/app/(app)/(protected)/app/entries/page.tsx
"use client";

import { useEntries } from "@/contexts/EntriesContext";
import EntryCard from "@/components/app/entries/EntryCard";
import EmptyState from "@/components/app/entries/EmptyState";
import EntriesHeader from "@/components/app/entries/EntriesHeader";
import LoadingText from "@/components/shared/LoadingText";
import { ScrollArea } from "@/components/ui/scroll-area";

export default function EntriesPage() {
  const { entries, isLoading } = useEntries();

  if (isLoading)
    return (
      <div className="text-muted-foreground flex h-full items-center justify-center text-6xl">
        <LoadingText />
      </div>
    );

  return (
    <main className="flex h-full flex-col px-10 pt-12">
      <EntriesHeader entriesCount={entries.length} />{" "}
      {entries.length === 0 ? (
        <EmptyState />
      ) : (
        <ScrollArea className="min-h-0 flex-1">
          <div className="mr-3 space-y-2 pb-6">
            {entries.map((entry) => (
              <EntryCard key={entry.id} entry={entry} />
            ))}
          </div>
        </ScrollArea>
      )}
    </main>
  );
}
