// src/components/landing/sections/Start.tsx
import CtaButton from "../CtaButton";

export default function Start() {
  return (
    <section
      className="bg-background relative overflow-hidden px-8 py-32 lg:py-52"
      id="start"
    >
      <div className="bg-secondary/40 absolute inset-x-0 bottom-0 -z-10 h-full w-full rounded-t-[100px] opacity-50 blur-3xl" />

      <div className="mx-auto max-w-4xl text-center">
        <div className="space-y-6">
          <h2 className="font-display text-foreground text-6xl font-normal tracking-tighter sm:text-7xl lg:text-8xl">
            ready to rest?
          </h2>

          <p className="font-primary text-muted-foreground mx-auto max-w-md text-xl leading-relaxed lg:text-2xl">
            start your journey at your own pace.
          </p>
        </div>

        <div className="mt-2 flex flex-col items-center gap-6">
          <CtaButton />
        </div>
      </div>
    </section>
  );
}

// src/lib/components/landing/sections/Start.svelte
<section class="relative overflow-hidden bg-background px-8 py-32 lg:py-52" id="start">
	<div
		class="absolute inset-x-0 bottom-0 -z-10 h-full w-full rounded-t-[100px] bg-secondary/40 opacity-50 blur-3xl"
	/>

	<div class="mx-auto max-w-4xl text-center">
		<div class="space-y-6">
			<h2
				class="font-display text-6xl font-normal tracking-tighter text-foreground sm:text-7xl lg:text-8xl"
			>
				ready to rest?
			</h2>

			<p
				class="font-primary mx-auto max-w-md text-xl leading-relaxed text-muted-foreground lg:text-2xl"
			>
				start your journey at your own pace.
			</p>
		</div>

		<div class="mt-2 flex flex-col items-center gap-6">
			<a
				href="/signup"
				class="font-primary inline-block min-w-60 rounded-2xl bg-primary px-12 py-5 text-center text-2xl font-bold text-primary-foreground transition-all duration-200 hover:brightness-110 active:scale-95 active:brightness-90"
			>
				start my journey!
			</a>
		</div>
	</div>
</section>
