// src/components/app/entries/EmptyState.tsx
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function EmptyState() {
  return (
    <div className="text-muted-foreground -mt-52 flex h-screen flex-col items-center justify-center">
      <p className="text-4xl lowercase">no entries yet</p>
      <p className="mt-2 mb-4 text-3xl">^▽^</p>
      <Button asChild className="p-5! text-xl! tracking-wide">
        <Link href="/app/new">begin the story</Link>
      </Button>
    </div>
  );
}

// src/lib/components/app/entry/EmptyState.svelte
<script>
	import Button from '$lib/components/ui/button/button.svelte';
</script>

<div class="-mt-52 flex h-screen flex-col items-center justify-center text-muted-foreground">
	<p class="text-4xl lowercase">no entries yet</p>
	<p class="mt-2 mb-4 text-3xl">^▽^</p>
	<Button class="p-5! text-xl! tracking-wide" href="/app/new">begin the story</Button>
</div>
