// src/components/app/entries/EntryView.tsx
"use client";

import { Editor } from "@/components/app/editor/Editor";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/auth.context";
import { useEntries } from "@/contexts/EntriesContext";
import { ArrowLeft, Pencil, X, Check } from "lucide-react";
import Link from "next/link";
import { useState, useRef } from "react";
import { DecryptedEntry, updateEntry } from "@/services/app/entry.service";

export default function EntryView({
  entry: initialEntry,
}: {
  entry: DecryptedEntry;
}) {
  const { masterKey } = useAuth();
  const { refreshEntries } = useEntries();

  const [isEditing, setIsEditing] = useState(false);
  const [title, setTitle] = useState(initialEntry.title);

  const [displayedEntry, setDisplayedEntry] = useState(initialEntry);

  const contentRef = useRef(initialEntry.content ?? "");

  const handleSave = async () => {
    if (!masterKey) return;

    await updateEntry(initialEntry.id, masterKey, title, contentRef.current);
    await refreshEntries();

    setDisplayedEntry({
      ...displayedEntry,
      title: title,
      content: contentRef.current,
      updatedAt: new Date().toISOString(),
    });

    setIsEditing(false);
  };

  const handleCancel = () => {
    setTitle(displayedEntry.title);
    contentRef.current = displayedEntry.content ?? "";
    setIsEditing(false);
  };

  return (
    <>
      {/* header */}
      <div className="mt-auto mb-4 flex flex-row items-center justify-between">
        <Button
          variant="ghost"
          asChild
          className="flex items-center px-3! py-6! text-2xl"
        >
          <Link href="/app/entries">
            <ArrowLeft className="mt-1 -mr-0.5" />
            entries
          </Link>
        </Button>

        {isEditing ? (
          <div className="flex gap-2">
            <Button
              variant="secondary"
              onClick={handleCancel}
              className="flex h-10! w-10! items-center justify-center rounded-full"
            >
              <X className="h-5! w-5! stroke-3!" />
            </Button>
            <Button
              variant="default"
              onClick={handleSave}
              className="flex h-10! w-10! items-center justify-center rounded-full"
            >
              <Check className="h-5! w-5! stroke-3!" />
            </Button>
          </div>
        ) : (
          <Button
            variant="default"
            onClick={() => setIsEditing(true)}
            className="flex h-10! w-10! items-center justify-center rounded-full"
          >
            <Pencil className="h-5! w-5! stroke-3!" />
          </Button>
        )}
      </div>

      {/* título */}
      <div className="px-2">
        <input
          placeholder="untitled entry"
          type="text"
          value={title}
          disabled={!isEditing}
          onChange={(e) => setTitle(e.target.value)}
          className="placeholder:text-muted-foreground border-accent mb-4 w-full border-b-2 bg-transparent text-2xl outline-none"
        />
      </div>

      {/* editor */}
      <div className="flex min-h-0 flex-1 flex-col rounded-sm border-2 bg-white/80 py-2">
        <Editor
          key={`${isEditing ? "editing" : "viewing"}-${displayedEntry.updatedAt}`}
          initialContent={displayedEntry.content ?? ""}
          editable={isEditing}
          onChange={(json) => {
            contentRef.current = json;
          }}
        />
      </div>
    </>
  );
}

// src/lib/components/app/entry/EntryView.svelte
<script lang="ts">
	import Editor from '$lib/components/app/editor/Editor.svelte';
	import { Button } from '$lib/components/ui/button';
	import { getAuthContext } from '$lib/contexts/auth.context.svelte';
	import { getAppContext } from '$lib/contexts/app.context.svelte';
	import { ArrowLeft, Pencil, X, Check } from '@lucide/svelte';
	import { updateEntry, type DecryptedEntry } from '$lib/services/app/entry.service';
	import { resolve } from '$app/paths';

	interface Props {
		entry: DecryptedEntry;
	}

	let { entry: initialEntry }: Props = $props();

	const { masterKey } = getAuthContext();
	const { refreshEntries } = getAppContext();

	let isEditing = $state(false);
	let title = $state('');
	let displayedEntry = $state<DecryptedEntry | null>(null);
	let currentContent = $state('');

	$effect(() => {
		title = initialEntry.title;
		displayedEntry = initialEntry;
		currentContent = initialEntry.content ?? '';
	});

	const handleSave = async () => {
		if (!masterKey || !displayedEntry) return;
		await updateEntry(initialEntry.id, masterKey, title, currentContent);
		await refreshEntries();
		displayedEntry = {
			...displayedEntry,
			title,
			content: currentContent,
			updatedAt: new Date().toISOString()
		};
		isEditing = false;
	};

	const handleCancel = () => {
		if (!displayedEntry) return;
		title = displayedEntry.title;
		currentContent = displayedEntry.content ?? '';
		isEditing = false;
	};
</script>

<div class="mt-auto mb-4 flex flex-row items-center justify-between">
	<Button
		variant="ghost"
		class="flex items-center gap-1 px-3! py-6! text-2xl"
		href={resolve('/app/entries')}
	>
		<ArrowLeft class="mt-1 -mr-0.5" />
		entries
	</Button>

	{#if isEditing}
		<div class="flex gap-2">
			<Button
				variant="secondary"
				onclick={handleCancel}
				class="flex h-10! w-10! items-center justify-center rounded-full"
			>
				<X class="h-5! w-5! stroke-3!" />
			</Button>
			<Button
				variant="default"
				onclick={handleSave}
				class="flex h-10! w-10! items-center justify-center rounded-full"
			>
				<Check class="h-5! w-5! stroke-3!" />
			</Button>
		</div>
	{:else}
		<Button
			variant="default"
			onclick={() => (isEditing = true)}
			class="flex h-10! w-10! items-center justify-center rounded-full"
		>
			<Pencil class="h-5! w-5! stroke-3!" />
		</Button>
	{/if}
</div>

<div class="px-2">
	<input
		placeholder="untitled entry"
		type="text"
		value={title}
		disabled={!isEditing}
		oninput={(e) => (title = e.currentTarget.value)}
		class="mb-4 w-full border-b-2 border-accent bg-transparent text-2xl outline-none placeholder:text-muted-foreground"
	/>
</div>

<div class="flex min-h-0 flex-1 flex-col rounded-sm border-2 bg-white/80 py-2">
	{#if displayedEntry}
		{#key `${isEditing ? 'editing' : 'viewing'}-${displayedEntry.updatedAt}`}
			<Editor
				initialContent={displayedEntry.content ?? ''}
				editable={isEditing}
				onChange={(json) => (currentContent = json)}
			/>
		{/key}
	{/if}
</div>
