// src/components/landing/FeatureCard.tsx
import { LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";

export interface FeatureCardProps {
  icon: LucideIcon;
  title: string;
  text: string;
}

export function FeatureCard({ icon: Icon, title, text }: FeatureCardProps) {
  return (
    <article
      className={cn(
        "group relative flex flex-col p-8",
        "border-border rounded-xl border",
        "bg-secondary transition-colors duration-300 ease-in-out",
        "hover:bg-accent",
      )}
    >
      <div className="bg-background border-border/50 text-primary mb-6 inline-flex h-12 w-12 items-center justify-center rounded-lg border">
        <Icon className="h-6 w-6 stroke-[1.5]" />
      </div>

      <div className="space-y-3">
        <h3 className="font-display text-foreground text-3xl font-medium tracking-normal">
          {title.toLowerCase()}
        </h3>
        <p className="font-primary text-muted-foreground text-2xl leading-relaxed text-pretty">
          {text}
        </p>
      </div>
    </article>
  );
}

// src/lib/components/landing/FeatureCard.svelte
<script lang="ts">
	import type { Component } from 'svelte';
	import { cn } from '$lib/utils';

	interface FeatureCardProps {
		icon: Component;
		title: string;
		text: string;
	}

	let { icon: Icon, title, text }: FeatureCardProps = $props();
</script>

<article
	class={cn(
		'group relative flex flex-col p-4 md:p-6 lg:p-8',
		'rounded-xl border border-border',
		'border-0 bg-secondary/50 transition-colors duration-300 ease-in-out',
		'hover:bg-accent/50'
	)}
>
	<div
		class="mb-6 inline-flex h-12 w-12 items-center justify-center rounded-lg border border-border/50 bg-background text-primary"
	>
		<Icon class="h-6 w-6 stroke-[1.5]" />
	</div>

	<div class="space-y-3">
		<h3 class="font-display text-3xl font-medium tracking-normal text-foreground">
			{title.toLowerCase()}
		</h3>
		<p class="font-primary text-2xl leading-relaxed text-pretty text-muted-foreground">
			{text}
		</p>
	</div>
</article>
