// src/lib/components/app/entry/EntryCard.svelte
<script lang="ts">
	import { getAppContext } from '$lib/contexts/app.context.svelte';
	import { deleteEntry, type DecryptedEntry } from '$lib/services/app/entry.service';
	import { Button } from '$lib/components/ui/button';
	import { Trash } from '@lucide/svelte';
	import * as AlertDialog from '$lib/components/ui/alert-dialog';
	import { resolve } from '$app/paths';

	interface Props {
		entry: DecryptedEntry;
	}
	let { entry }: Props = $props();

	const { refreshEntries } = getAppContext();

	let showDialog = $state(false);

	async function handleConfirmDelete(id: string) {
		await deleteEntry(id);
		await refreshEntries();
		showDialog = false;
	}
</script>

<AlertDialog.Root bind:open={showDialog}>
	<AlertDialog.Content>
		<AlertDialog.Header>
			<AlertDialog.Title class="text-3xl! tracking-wide">
				delete "{entry.title}" entry?
			</AlertDialog.Title>
			<AlertDialog.Description class="text-xl tracking-wide text-muted-foreground">
				this entry will be lost forever! (a long time!)
			</AlertDialog.Description>
		</AlertDialog.Header>
		<AlertDialog.Footer>
			<AlertDialog.Cancel class="cursor-pointer text-lg! tracking-wide!">cancel</AlertDialog.Cancel>
			<AlertDialog.Action
				variant="destructive"
				class="cursor-pointer bg-destructive/20! text-lg! tracking-wider! text-destructive! hover:bg-destructive/30!"
				onclick={() => handleConfirmDelete(entry.id)}
			>
				delete
			</AlertDialog.Action>
		</AlertDialog.Footer>
	</AlertDialog.Content>
</AlertDialog.Root>

<a
	href={resolve(`/app/entries/${entry.id}`)}
	class="group flex items-center rounded-xl border border-border p-4 transition-all hover:bg-accent"
>
	<div class="flex-1">
		<p class="text-xl">{entry.title}</p>
		<p class="mt-1 text-base text-muted-foreground">
			{entry.date} · {entry.time}
		</p>
	</div>

	<Button
		variant="ghost"
		class="mr-2 hidden h-12 w-12 cursor-pointer items-center justify-center rounded-full p-0! group-hover:flex hover:bg-destructive/20 hover:text-destructive"
		onclick={(e) => {
			e.stopPropagation();
			e.preventDefault();
			showDialog = true;
		}}
	>
		<Trash class="h-6! w-6! stroke-2" />
	</Button>
</a>

// src/components/app/entries/EntryCard.tsx
import Link from "next/link";
import { DecryptedEntry, deleteEntry } from "@/services/app/entry.service";
import { Button } from "@/components/ui/button";
import { Trash } from "lucide-react";
import { useEntries } from "@/contexts/EntriesContext";
import { useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

export default function EntryCard({ entry }: { entry: DecryptedEntry }) {
  const { refreshEntries } = useEntries();
  const [showDialog, setShowDialog] = useState(false);

  function handleConfirmDelete(id: string) {
    deleteEntry(id);
    refreshEntries();
  }

  return (
    <>
      <AlertDialog open={showDialog} onOpenChange={setShowDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="text-3xl! tracking-wide">
              delete &quot;{entry.title}&quot; entry?
            </AlertDialogTitle>
            <AlertDialogDescription className="text-muted-foreground text-xl tracking-wide">
              this entry will be lost forever! (a long time!)
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="cursor-pointer text-lg! tracking-wide!">
              cancel
            </AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              className="text-destructive! bg-destructive/20! hover:bg-destructive/30! cursor-pointer text-lg! tracking-wider!"
              onClick={() => handleConfirmDelete(entry.id)}
            >
              delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Link
        href={`/app/entries/${entry.id}`}
        className="hover:bg-accent border-border group flex items-center rounded-xl border p-4 transition-all"
      >
        <div className="flex-1">
          <p className="text-xl">{entry.title}</p>
          <p className="text-muted-foreground mt-1 text-base">
            {entry.date} · {entry.time}
          </p>
        </div>

        <Button
          variant="ghost"
          className="hover:text-destructive hover:bg-destructive/20 mr-2 hidden h-12 w-12 cursor-pointer items-center justify-center rounded-full p-0! group-hover:flex"
          onClick={(e) => {
            e.stopPropagation();
            e.preventDefault();
            setShowDialog(true);
          }}
        >
          <Trash className="h-6! w-6! stroke-2" />
        </Button>
      </Link>
    </>
  );
}
