// src/app/(app)/(auth)/signup/page.tsx
"use client";

import { useSignup } from "@/hooks/signup/useSignup";
import { formFields } from "@/data/signup/formFields";
import FormField from "@/components/signup/FormField";
import { Button } from "@/components/ui/button";
import Link from "next/link";

/**
 * pagina de /signup
 */
export default function Signup() {
  const { formData, error, isLoading, isChecking, handleChange, handleSubmit } =
    useSignup();

  if (isChecking) return null;

  return (
    <main className="flex min-h-screen items-center justify-center px-8 py-16">
      <div className="w-full max-w-2xl">
        <div className="border-border bg-card rounded-xl border shadow-lg lg:px-12 lg:py-8 lg:pb-4">
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* cabecera */}
            <h1 className="text-foreground mb-8 text-4xl font-bold lg:text-5xl">
              welcome to shelter!
            </h1>

            {/* formulario */}
            <div className="space-y-4">
              {formFields.map((field) => (
                <FormField
                  key={field.id}
                  field={field}
                  value={formData[field.name as keyof typeof formData]}
                  onChange={handleChange}
                  disabled={isLoading}
                />
              ))}
            </div>

            {/* error escondido */}
            {error && (
              <p className="text-destructive text-sm font-medium">{error}</p>
            )}

            {/* botones */}
            <Button
              type="submit"
              className="bg-primary text-primary-foreground hover:bg-primary/85 w-full text-lg tracking-wide"
              size="lg"
              disabled={isLoading}
            >
              {isLoading ? "creating your diary..." : "create my diary"}
            </Button>
          </form>

          <p className="text-muted-foreground text-md mt-4 text-center">
            already have a diary?{" "}
            <Link
              className="text-primary-dark hover:text-primary font-medium underline transition-colors"
              href="/restore"
            >
              restore
            </Link>
          </p>
        </div>
      </div>
    </main>
  );
}

// src/routes/(auth)/signup/+page.svelte
<script lang="ts">
	import { useSignup } from '$lib/hooks/signup/useSignup.svelte';
	import { formFields } from '$lib/constants/signup/formFields';
	import FormField from '$lib/components/signup/FormField.svelte';
	import { Button } from '$lib/components/ui/button';
	import { resolve } from '$app/paths';

	const signup = useSignup();
</script>

{#if signup.isChecking}
	<!-- add loading? -->
	<!-- <div class="flex min-h-screen items-center justify-center">
		<div class="h-8 w-8 animate-spin rounded-full border-b-2 border-primary"></div>
	</div> -->
	<div></div>
{:else}
	<main class="flex min-h-screen items-center justify-center px-8 py-16">
		<div class="w-full max-w-2xl">
			<div class="rounded-xl border bg-card px-4 py-3 shadow-lg md:px-8 md:py-6 lg:px-12 lg:py-8">
				<form onsubmit={signup.handleSubmit} class="space-y-6">
					<!-- header -->
					<h1 class="mb-8 text-4xl font-bold text-foreground lg:text-5xl">welcome to shelter!</h1>

					<!-- form -->
					<div class="space-y-4">
						{#each formFields as field (field.id)}
							<FormField
								{field}
								value={signup.formData[field.name]}
								onChange={signup.handleChange}
								disabled={signup.isLoading}
							/>
						{/each}
					</div>

					<!-- err -->
					{#if signup.error}
						<p class="text-sm font-medium text-destructive">{signup.error}</p>
					{/if}

					<!-- btn -->
					<Button
						type="submit"
						class="w-full bg-primary text-lg tracking-wide text-primary-foreground hover:bg-primary/85"
						size="lg"
						disabled={signup.isLoading}
					>
						{signup.isLoading ? 'creating your diary...' : 'create my diary'}
					</Button>
				</form>

				<p class="text-md mt-4 text-center text-muted-foreground">
					already have a diary?
					<a
						class="text-primary-dark font-medium underline transition-colors hover:text-primary"
						href={resolve('/restore')}
					>
						restore
					</a>
				</p>
			</div>
		</div>
	</main>
{/if}
