// src/app/(app)/(protected)/app/entries/[id]/page.tsx
"use client";

import EntryView from "@/components/app/entries/EntryView";
import LoadingText from "@/components/shared/LoadingText";
import { useEntry } from "@/hooks/app/useEntry";
import { useParams } from "next/navigation";

export default function EntryContent() {
  const params = useParams();
  const id = Array.isArray(params.id) ? params.id[0] : params.id;

  const { entry, isLoading, error } = useEntry(id || "");

  // fallos
  if (!id) return <Centered>no id</Centered>; // id tiene q ir primero para ver si existe
  if (error) return <Centered>{error}</Centered>; // comprobar si hay error
  if (isLoading)
    return <Centered>{LoadingText({ text: "loading entry" })}</Centered>; // en caso q exista, se pone loading
  if (!entry) return <Centered>entry not found</Centered>; // en caso raro que no se encuentra?

  return (
    <main className="flex h-full flex-col px-12 py-6">
      <EntryView entry={entry} />
    </main>
  );
}

function Centered({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-foreground flex h-full w-full items-center justify-center text-4xl tracking-wide">
      {children}
    </div>
  );
}

// src/routes/(auth)/app/entries/[id]/+page.svelte
<script lang="ts">
	import EntryView from '$lib/components/app/entry/EntryView.svelte';
	import LoadingText from '$lib/components/shared/LoadingText.svelte';
	import { useEntry } from '$lib/hooks/app/useEntry.svelte';
	import type { PageProps } from './$types';

	const { params }: PageProps = $props();

	const entryState = $derived(useEntry(params.id));
</script>

{#if !params.id}
	<div
		class="flex h-full w-full items-center justify-center text-2xl tracking-wide text-foreground lg:text-4xl"
	>
		no id
	</div>
{:else if entryState.error}
	<div
		class="flex h-full w-full items-center justify-center text-2xl tracking-wide text-foreground lg:text-4xl"
	>
		{entryState.error}
	</div>
{:else if entryState.isLoading}
	<div
		class="flex h-full w-full items-center justify-center text-2xl tracking-wide text-foreground lg:text-4xl"
	>
		<LoadingText text="loading entry" />
	</div>
{:else if !entryState.entry}
	<div
		class="flex h-full w-full items-center justify-center text-2xl tracking-wide text-foreground lg:text-4xl"
	>
		entry not found
	</div>
{:else}
	<main class="flex h-full flex-col px-4 py-4 lg:px-12 lg:py-6">
		<EntryView entry={entryState.entry} />
	</main>
{/if}
