// src/lib/components/landing/sections/Footer.svelte
<script lang="ts">
	import FooterLink from '../FooterLink.svelte';

	const currentYear = new Date().getFullYear();
</script>

<footer class="w-full border-t border-border/40 bg-background pt-16 pb-12">
	<div class="mx-auto w-11/12 max-w-7xl">
		<div class="grid grid-cols-1 gap-12 md:grid-cols-2 lg:grid-cols-4">
			<div class="space-y-4">
				<p class="font-display text-3xl font-normal tracking-tighter text-foreground">shelter</p>
				<div class="font-primary space-y-1 text-sm leading-relaxed text-muted-foreground/60">
					<p>© 2025–{currentYear} shelter</p>
					<p>all rights reserved</p>
				</div>
			</div>

			<!-- Product Section -->
			<div class="space-y-4">
				<p class="font-display text-lg font-medium tracking-tight text-foreground">product</p>
				<nav class="font-primary flex flex-col space-y-2.5">
					<FooterLink href="">about us</FooterLink>
					<FooterLink href="">cloud</FooterLink>
					<FooterLink href="">self-host</FooterLink>
				</nav>
			</div>

			<div class="space-y-4">
				<p class="font-display text-lg font-medium tracking-tight text-foreground">legal</p>
				<nav class="font-primary flex flex-col space-y-2.5">
					<FooterLink href="/privacy">privacy policy</FooterLink>
					<FooterLink href="/terms">terms of service</FooterLink>
					<FooterLink href="/cookies">cookie policy</FooterLink>
				</nav>
			</div>

			<div class="space-y-4">
				<p class="font-display text-lg font-medium tracking-tight text-foreground">contact</p>
				<nav class="font-primary flex flex-col space-y-2.5">
					<FooterLink href="https://github.com/Stageddat/shelter-web" external>github</FooterLink>
					<FooterLink href="mailto:hello@stageddat.dev">hello@stageddat.dev</FooterLink>
				</nav>
			</div>
		</div>
	</div>
</footer>

// src/components/landing/sections/Footer.tsx
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="border-border mx-auto mt-16 w-11/12 max-w-7xl border-t pt-8 pb-6">
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
        {/* project section */}
        <div className="space-y-3">
          <p className="text-foreground text-2xl font-semibold">shelter</p>
          <div className="text-muted-foreground space-y-1 text-sm">
            <p>© 2025-{new Date().getFullYear()} shelter</p>
            <p>all rights reserved</p>
          </div>
        </div>

        {/* shelter section */}
        <div className="space-y-3">
          <p className="text-foreground text-sm font-semibold tracking-wider uppercase">
            Product
          </p>
          {/* TODO: add links */}
          <nav className="flex flex-col space-y-2">
            <Link
              href=""
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
            >
              about us
            </Link>
            <Link
              href=""
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
            >
              cloud
            </Link>
            <Link
              href=""
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
            >
              self-host
            </Link>
          </nav>
        </div>

        {/* legal section */}
        <div className="space-y-3">
          <p className="text-foreground text-sm font-semibold tracking-wider uppercase">
            Legal
          </p>
          <nav className="flex flex-col space-y-2">
            <Link
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
              href="/privacy"
            >
              privacy policy
            </Link>
            <Link
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
              href="/terms"
            >
              terms of service
            </Link>
            <Link
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
              href="/cookies"
            >
              cookie policy
            </Link>
          </nav>
        </div>

        {/* contact section */}
        <div className="space-y-3">
          <p className="text-foreground text-sm font-semibold tracking-wider uppercase">
            Contact
          </p>
          <nav className="flex flex-col space-y-2">
            {/* <Link
              // TODO: add discord
              href=""
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
            >
              discord
            </Link> */}
            <Link
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
              href="https://github.com/Stageddat/shelter-web"
              target="_blank"
              rel="noopener noreferrer"
            >
              github
            </Link>
            <Link
              className="text-muted-foreground hover:text-foreground text-sm transition-colors"
              href="mailto:hello@stageddat.dev"
            >
              hello@stageddat.dev
            </Link>
          </nav>
        </div>
      </div>
    </footer>
  );
}
