// src/lib/components/landing/sections/Navbar.svelte
<script lang="ts">
	import Menu from '@lucide/svelte/icons/menu';
	import * as NavigationMenu from '$lib/components/ui/navigation-menu/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Sheet from '$lib/components/ui/sheet/index.js';

	const NAV_LINKS = [
		{ href: '/#features', label: 'features' },
		{ href: '/#security', label: 'security' },
		{ href: '/#faqs', label: 'faqs' }
	];

	let sheetOpen = $state(false);
</script>

<header
	class="fixed top-0 z-50 w-full border-b border-border/20 bg-background/60 backdrop-blur-xl transition-all duration-300"
>
	<div class="container mx-auto flex h-20 max-w-7xl items-center justify-between px-6">
		<div class="flex items-center gap-8">
			<!-- Mobile menu -->
			<Sheet.Root bind:open={sheetOpen}>
				<Sheet.Trigger
					class="flex h-10 w-10 items-center justify-center rounded-2xl border border-border/40 bg-secondary/80 transition-colors md:hidden"
				>
					<Menu class="h-5 w-5 text-foreground" />
				</Sheet.Trigger>

				<Sheet.Content side="left" class="w-80 border-r border-border/20 bg-background p-0">
					<div class="flex h-full flex-col p-10">
						<p class="font-display mb-12 text-3xl tracking-tighter text-foreground">shelter</p>
						<nav class="flex flex-col gap-8">
							{#each NAV_LINKS as { href, label }}
								<Sheet.Close>
									<a
										{href}
										class="font-display text-3xl tracking-tight text-muted-foreground transition-colors hover:text-primary"
									>
										{label}
									</a>
								</Sheet.Close>
							{/each}
						</nav>
					</div>
				</Sheet.Content>
			</Sheet.Root>

			<!-- Logo -->
			<a
				href="/"
				class="font-primary flex items-center text-2xl tracking-wide transition-opacity hover:opacity-80 lg:text-3xl"
			>
				<span class="relative -top-px">shelter</span>
			</a>

			<!-- Desktop nav -->
			<NavigationMenu.Root class="hidden md:flex">
				<NavigationMenu.List class="gap-1">
					{#each NAV_LINKS as { href, label }}
						<NavigationMenu.Item>
							<NavigationMenu.Link
								{href}
								class="font-primary rounded-full bg-transparent px-4 text-xl tracking-tight text-muted-foreground transition-colors hover:bg-secondary/80 hover:text-foreground lg:text-3xl"
							>
								{label}
							</NavigationMenu.Link>
						</NavigationMenu.Item>
					{/each}
				</NavigationMenu.List>
			</NavigationMenu.Root>
		</div>

		<!-- CTA -->
		<Button
			href="/signup"
			class="hidden h-10 bg-primary px-4 py-2 text-2xl shadow-lg shadow-foreground/5 transition-all hover:bg-primary/85 sm:inline-flex"
		>
			get started
		</Button>
	</div>
</header>

// src/components/landing/sections/Navbar.tsx
"use client";

import Link from "next/link";
import { Menu } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import {
  Sheet,
  SheetContent,
  SheetTrigger,
  SheetClose,
} from "@/components/ui/sheet";

const NAV_LINKS = [
  { href: "/#features", label: "features" },
  { href: "/#security", label: "security" },
  { href: "/#faqs", label: "faqs" },
];

function MobileMenu() {
  return (
    <Sheet>
      <SheetTrigger className="border-border/40 bg-secondary/80 flex h-10 w-10 items-center justify-center rounded-2xl border transition-colors md:hidden">
        <Menu className="text-foreground h-5 w-5" />
      </SheetTrigger>

      <SheetContent
        side="left"
        className="border-border/20 bg-background w-80 border-r p-0"
      >
        <div className="flex h-full flex-col p-10">
          <p className="font-display text-foreground mb-12 text-3xl tracking-tighter">
            shelter
          </p>
          <nav className="flex flex-col gap-8">
            {NAV_LINKS.map(({ href, label }) => (
              <SheetClose asChild key={href}>
                <Link
                  href={href}
                  className="font-display text-muted-foreground hover:text-primary text-3xl tracking-tight transition-colors"
                >
                  {label}
                </Link>
              </SheetClose>
            ))}
          </nav>
        </div>
      </SheetContent>
    </Sheet>
  );
}

function DesktopNav() {
  return (
    <NavigationMenu className="hidden md:flex">
      <NavigationMenuList className="gap-1">
        {NAV_LINKS.map(({ href, label }) => (
          <NavigationMenuItem key={`nav-${label}`}>
            <NavigationMenuLink
              asChild
              className={cn(
                navigationMenuTriggerStyle(),
                "hover:bg-secondary/80 text-muted-foreground hover:text-foreground font-primary rounded-full bg-transparent px-4 text-xl tracking-tight transition-colors lg:text-3xl",
              )}
            >
              <Link href={href}>{label}</Link>
            </NavigationMenuLink>
          </NavigationMenuItem>
        ))}
      </NavigationMenuList>
    </NavigationMenu>
  );
}

export default function Navbar() {
  return (
    <header className="border-border/20 bg-background/60 fixed top-0 z-50 w-full border-b backdrop-blur-xl transition-all duration-300">
      <div className="container mx-auto flex h-20 max-w-7xl items-center justify-between px-6">
        <div className="flex items-center gap-8">
          <MobileMenu />
          <Link
            href="/"
            className="font-primary flex items-center text-2xl tracking-wide transition-opacity hover:opacity-80 lg:text-3xl"
          >
            <span className="relative -top-px">shelter</span>
          </Link>
          <DesktopNav />
        </div>

        {/* CTA */}
        <Button
          asChild
          className="bg-primary hover:bg-primary/85 shadow-foreground/5 hidden h-10 px-4 py-2 text-2xl shadow-lg transition-all sm:inline-flex"
        >
          <Link href="/signup">get started</Link>
        </Button>
      </div>
    </header>
  );
}
