// src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import LoginForm from '$lib/components/login/LoginForm.svelte';
	import { useLogin } from '$lib/hooks/login/useLogin.svelte';

	const login = useLogin();
</script>

{#if login.username}
	<main class="flex min-h-screen items-center justify-center px-8 py-16">
		<div class="w-full max-w-2xl">
			<div class="rounded-xl border bg-card px-4 py-3 shadow-lg md:px-8 md:py-6 lg:px-12 lg:py-8">
				<LoginForm
					username={login.username}
					password={login.password}
					handleChange={login.handleChange}
					handleSubmit={login.handleSubmit}
					isLoading={login.isLoading}
					error={login.error}
				/>
			</div>
		</div>
	</main>
{/if}

// src/app/(protected)/login/page.tsx
"use client";

import LoginForm from "@/components/login/loginForm";
import Link from "next/link";

export default function Login() {
  return (
    <main className="flex min-h-screen items-center justify-center px-8 py-16">
      <div className="w-full max-w-2xl space-y-8">
        <div className="border-border bg-card rounded-xl border p-8 shadow-lg lg:p-12">
          <LoginForm />
        </div>

        <p className="text-muted-foreground text-center text-sm">
          don’t have an account?{" "}
          <Link
            className="text-primary-dark hover:text-primary font-medium underline transition-colors"
            href="/signup"
          >
            sign up
          </Link>
        </p>
      </div>
    </main>
  );
}
